### ISSUE TITLE
Project screenshots

### ISSUE THREAD

**Issue by elyor-doniyorov** [elyor-doniyorov/Capstone-Project-Pet-s-Shop#2]
Project Screenshots
"About" is a link to the result page

**Comment by EL28DEV** [comment]
![Capstone Project](https://user-images.githubusercontent.com/67087664/106931160-16022180-6738-11eb-93bf-a63755dd6e09.png)
![search-page](https://user-images.githubusercontent.com/67087664/106932024-0931fd80-6739-11eb-8f87-3784a2c3aa4e.png)

**Comment by elyor-doniyorov** [comment]
![home-page](https://user-images.githubusercontent.com/67087664/106937061-21a51680-673f-11eb-89b4-313f1f60bd8a.png)
![search-page](https://user-images.githubusercontent.com/67087664/106937091-2c5fab80-673f-11eb-8f07-db772500c10c.png)
![Screenshot (292)](https://user-images.githubusercontent.com/67087664/106937170-4600f300-673f-11eb-9563-4d5377fae89a.png)
![Screenshot (293)](https://user-images.githubusercontent.com/67087664/106937259-603ad100-673f-11eb-936c-92925a2fefb6.png)
